gzip on;
gzip_disable "msie6";

gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_min_length 256;
gzip_types
  application/atom+xml
  application/geo+json
  application/javascript
  application/x-javascript
  application/json
  application/ld+json
  application/manifest+json
  application/rdf+xml
  application/rss+xml
  application/xhtml+xml
  application/xml
  font/eot
  font/otf
  font/ttf
  image/svg+xml
  text/css
  text/javascript
  text/plain
  text/xml;


server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # 已添加内容哈希的文件可设置较长的缓存时间
    location ~ .*\.(gif|jpg|jpeg|png|mp3|ttf|css|js)$ {
        add_header Cache-Control max-age=31536000;
    }

    location / {
        add_header Cache-Control 'no-store, max-age=0';
        try_files $uri $uri/ =404;
    }

    error_page 404 /;
}
