version: "3.8"

services:
  woodpecker-agent-1:
    image: woodpeckerci/woodpecker-agent:v3.5.0
    container_name: woodpecker-agent-1
    hostname: oracle-cloud-worker-1
    restart: always
    environment:
      WOODPECKER_SERVER: c6.shafayouxi.org:9001
      WOODPECKER_AGENT_SECRET: XKFAY43JVCGLXZO45VH2PSQL3OGLUX63GAZJXKLMILHXUS7U75GA====
      WOODPECKER_AGENT_NAME: oracle-cloud-worker-1
      WOODPECKER_BACKEND: docker
      WOODPECKER_MAX_WORKFLOWS: 2
      WOODPECKER_FILTER_LABELS: repo=kevinanew/laiwan_react_native,laiwan-react-native=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent-1:/etc/woodpecker

  woodpecker-agent-2:
    image: woodpeckerci/woodpecker-agent:v3.5.0
    container_name: woodpecker-agent-2
    hostname: oracle-cloud-worker-2
    restart: always
    environment:
      WOODPECKER_SERVER: c6.shafayouxi.org:9001
      WOODPECKER_AGENT_SECRET: 5BPT2DWIWQITVUZMXV7C77OCGGMBCSDJQJBZNBG2U6ZIGXGRZITQ====
      WOODPECKER_AGENT_NAME: oracle-cloud-worker-2
      WOODPECKER_BACKEND: docker
      WOODPECKER_MAX_WORKFLOWS: 2
      WOODPECKER_FILTER_LABELS: repo=kevinanew/laiwan_react_native,laiwan-react-native=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent-2:/etc/woodpecker
